/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DbRouteImport } from './routes/db'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DbDbIdRouteImport } from './routes/db/$dbId'
import { Route as DbDbIdSettingsRouteImport } from './routes/db/$dbId/settings'
import { Route as DbDbIdLogsRouteImport } from './routes/db/$dbId/logs'
import { Route as DbDbIdInfoRouteImport } from './routes/db/$dbId/info'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DbRoute = DbRouteImport.update({
  id: '/db',
  path: '/db',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DbDbIdRoute = DbDbIdRouteImport.update({
  id: '/$dbId',
  path: '/$dbId',
  getParentRoute: () => DbRoute,
} as any)
const DbDbIdSettingsRoute = DbDbIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DbDbIdRoute,
} as any)
const DbDbIdLogsRoute = DbDbIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DbDbIdRoute,
} as any)
const DbDbIdInfoRoute = DbDbIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => DbDbIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/db': typeof DbRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/db/$dbId': typeof DbDbIdRouteWithChildren
  '/db/$dbId/info': typeof DbDbIdInfoRoute
  '/db/$dbId/logs': typeof DbDbIdLogsRoute
  '/db/$dbId/settings': typeof DbDbIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/db': typeof DbRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/db/$dbId': typeof DbDbIdRouteWithChildren
  '/db/$dbId/info': typeof DbDbIdInfoRoute
  '/db/$dbId/logs': typeof DbDbIdLogsRoute
  '/db/$dbId/settings': typeof DbDbIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/db': typeof DbRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/db/$dbId': typeof DbDbIdRouteWithChildren
  '/db/$dbId/info': typeof DbDbIdInfoRoute
  '/db/$dbId/logs': typeof DbDbIdLogsRoute
  '/db/$dbId/settings': typeof DbDbIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/db'
    | '/login'
    | '/setup'
    | '/db/$dbId'
    | '/db/$dbId/info'
    | '/db/$dbId/logs'
    | '/db/$dbId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/db'
    | '/login'
    | '/setup'
    | '/db/$dbId'
    | '/db/$dbId/info'
    | '/db/$dbId/logs'
    | '/db/$dbId/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/db'
    | '/login'
    | '/setup'
    | '/db/$dbId'
    | '/db/$dbId/info'
    | '/db/$dbId/logs'
    | '/db/$dbId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DbRoute: typeof DbRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db': {
      id: '/db'
      path: '/db'
      fullPath: '/db'
      preLoaderRoute: typeof DbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$dbId': {
      id: '/db/$dbId'
      path: '/$dbId'
      fullPath: '/db/$dbId'
      preLoaderRoute: typeof DbDbIdRouteImport
      parentRoute: typeof DbRoute
    }
    '/db/$dbId/settings': {
      id: '/db/$dbId/settings'
      path: '/settings'
      fullPath: '/db/$dbId/settings'
      preLoaderRoute: typeof DbDbIdSettingsRouteImport
      parentRoute: typeof DbDbIdRoute
    }
    '/db/$dbId/logs': {
      id: '/db/$dbId/logs'
      path: '/logs'
      fullPath: '/db/$dbId/logs'
      preLoaderRoute: typeof DbDbIdLogsRouteImport
      parentRoute: typeof DbDbIdRoute
    }
    '/db/$dbId/info': {
      id: '/db/$dbId/info'
      path: '/info'
      fullPath: '/db/$dbId/info'
      preLoaderRoute: typeof DbDbIdInfoRouteImport
      parentRoute: typeof DbDbIdRoute
    }
  }
}

interface DbDbIdRouteChildren {
  DbDbIdInfoRoute: typeof DbDbIdInfoRoute
  DbDbIdLogsRoute: typeof DbDbIdLogsRoute
  DbDbIdSettingsRoute: typeof DbDbIdSettingsRoute
}

const DbDbIdRouteChildren: DbDbIdRouteChildren = {
  DbDbIdInfoRoute: DbDbIdInfoRoute,
  DbDbIdLogsRoute: DbDbIdLogsRoute,
  DbDbIdSettingsRoute: DbDbIdSettingsRoute,
}

const DbDbIdRouteWithChildren =
  DbDbIdRoute._addFileChildren(DbDbIdRouteChildren)

interface DbRouteChildren {
  DbDbIdRoute: typeof DbDbIdRouteWithChildren
}

const DbRouteChildren: DbRouteChildren = {
  DbDbIdRoute: DbDbIdRouteWithChildren,
}

const DbRouteWithChildren = DbRoute._addFileChildren(DbRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DbRoute: DbRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
